version: "3.8"

services:
  api:
    container_name: api-container
    environment:
      GO_ENV: ${GO_ENV}
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 9090:9090
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: db-container
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:7.0
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    restart: always
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin4-data:
